# Generated by Django 5.0.6 on 2024-05-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='azure_image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
