name: Build and deploy Python app to Azure Web App - resta

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar versión de Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Crear y activar entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # Opcional: Añadir paso para ejecutar pruebas aquí (PyTest, suites de pruebas de Django, etc.)

      - name: Comprimir artefacto para despliegue
        run: zip -r release.zip ./* -x "venv/*"

      - name: Subir artefacto para trabajos de despliegue
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es necesario para solicitar el JWT

    steps:
      - name: Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Descomprimir artefacto para despliegue
        run: unzip release.zip

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1186F6F52A9A4D208C2BBFBADFA3FF2D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCC8F43CB36D4715BF443BDEE42FF5A1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5678A28F6528458C8C8EDFE3042593CE }}

      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'resta'
          slot-name: 'production'
